export const globalCSSVariables = {
    primaryColor: "#1e3a8a",
    secondaryColor: "grey",
    successColor: "#059669",
    warningColor: "#FCD34D",
    errorColor: "#DC2626",
    bgColor: "#f8fafc",
    black: "#000000",
    lightGrey: "#eee",
    white: "#ffffff",
    highlight: "yellow",
    shadowColor: "rgba(0, 0, 0, 0.25)",
    primaryFf: '"Monserrat", sans-serif',
    secondaryFf: '"Poppins", sans-serif',
    codeFf: '"Courier New", Courier, monospace',
};
